ALTER TABLE angle_scores ADD COLUMN views INTEGER NOT NULL DEFAULT 0;

ALTER TABLE angle_scores ADD COLUMN attrition REAL NOT NULL DEFAULT 0;

ALTER TABLE angle_scores ADD COLUMN dwell_ms REAL NOT NULL DEFAULT 0;
