ALTER TABLE catalog_titles ADD COLUMN overview TEXT NOT NULL DEFAULT '';
ALTER TABLE catalog_titles ADD COLUMN release_date TEXT;
ALTER TABLE catalog_titles ADD COLUMN runtime_minutes INTEGER;
ALTER TABLE catalog_titles ADD COLUMN number_of_seasons INTEGER;
ALTER TABLE catalog_titles ADD COLUMN certification TEXT;
ALTER TABLE catalog_titles ADD COLUMN status TEXT;
ALTER TABLE catalog_titles ADD COLUMN original_language TEXT;
ALTER TABLE catalog_titles ADD COLUMN tmdb_score REAL;
ALTER TABLE catalog_titles ADD COLUMN poster_url TEXT;
ALTER TABLE catalog_titles ADD COLUMN backdrop_url TEXT;
ALTER TABLE catalog_titles ADD COLUMN watch_link TEXT;
ALTER TABLE catalog_titles ADD COLUMN revenue INTEGER;
ALTER TABLE catalog_titles ADD COLUMN collection_id INTEGER;
ALTER TABLE catalog_titles ADD COLUMN collection_name TEXT;
ALTER TABLE catalog_titles ADD COLUMN mal_id INTEGER;
ALTER TABLE catalog_titles ADD COLUMN anilist_id INTEGER;
ALTER TABLE catalog_titles ADD COLUMN wikidata_id TEXT;
